### ISSUE TITLE
unable to remove application right after adding one

### ISSUE THREAD

**Issue by netcsc** [DevOpsify/releaseMaster#46]
it seems _id is not created right way when adding an application so that remove call failed to remove application

**Comment by SiweiWang** [comment]
Interesting, id should be auto generated

**Comment by netcsc** [comment]
@SiweiWang maybe I did something wrong. if you have time, can you take a look at it ? almost close to beta release. LoL

**Comment by SiweiWang** [comment]
Sure, Beta? let's make it v1.0.0

**Comment by SiweiWang** [comment]
The issue with this is when application is created, the Angular model is not populated with the model from the mongo db hence it does not have the id. Move deletion using name resolves this

**Comment by SiweiWang** [comment]
Fixed in https://github.com/DevOpsify/releaseMaster/pull/50
